package clasesHibernate;
// Generated 29 abr 2025 14:45:43 by Hibernate Tools 6.5.1.Final

/**
 * Ciudades generated by hbm2java
 */
public class Ciudades implements java.io.Serializable {

	private int idCiudad;
	private Paises paises;
	private String nombre;
	private Float numHabitantes;
	private Float superficie;
	private Float kmLineaCosta;
	private Float km2Agua;
	private Float km2Tierra;

	public Ciudades() {
	}

	public Ciudades(int idCiudad) {
		this.idCiudad = idCiudad;
	}

	public Ciudades(int idCiudad, Paises paises, String nombre, Float numHabitantes, Float superficie,
			Float kmLineaCosta, Float km2Agua, Float km2Tierra) {
		this.idCiudad = idCiudad;
		this.paises = paises;
		this.nombre = nombre;
		this.numHabitantes = numHabitantes;
		this.superficie = superficie;
		this.kmLineaCosta = kmLineaCosta;
		this.km2Agua = km2Agua;
		this.km2Tierra = km2Tierra;
	}
	//Constructor añadido
	public Ciudades(Paises paises, String nombre, Float numHabitantes, Float superficie,
			Float kmLineaCosta, Float km2Agua, Float km2Tierra) {
		this.paises = paises;
		this.nombre = nombre;
		this.numHabitantes = numHabitantes;
		this.superficie = superficie;
		this.kmLineaCosta = kmLineaCosta;
		this.km2Agua = km2Agua;
		this.km2Tierra = km2Tierra;
	}
	public int getIdCiudad() {
		return this.idCiudad;
	}

	public void setIdCiudad(int idCiudad) {
		this.idCiudad = idCiudad;
	}

	public Paises getPaises() {
		return this.paises;
	}

	public void setPaises(Paises paises) {
		this.paises = paises;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Float getNumHabitantes() {
		return this.numHabitantes;
	}

	public void setNumHabitantes(Float numHabitantes) {
		this.numHabitantes = numHabitantes;
	}

	public Float getSuperficie() {
		return this.superficie;
	}

	public void setSuperficie(Float superficie) {
		this.superficie = superficie;
	}

	public Float getKmLineaCosta() {
		return this.kmLineaCosta;
	}

	public void setKmLineaCosta(Float kmLineaCosta) {
		this.kmLineaCosta = kmLineaCosta;
	}

	public Float getKm2Agua() {
		return this.km2Agua;
	}

	public void setKm2Agua(Float km2Agua) {
		this.km2Agua = km2Agua;
	}

	public Float getKm2Tierra() {
		return this.km2Tierra;
	}

	public void setKm2Tierra(Float km2Tierra) {
		this.km2Tierra = km2Tierra;
	}

}
