package clasesHibernate;
// Generated 29 abr 2025 14:45:43 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Idiomas generated by hbm2java
 */
public class Idiomas implements java.io.Serializable {

	private int idIdioma;
	private String idioma;
	private Set paiseses = new HashSet(0);

	public Idiomas() {
	}

	public Idiomas(int idIdioma) {
		this.idIdioma = idIdioma;
	}

	public Idiomas(int idIdioma, String idioma, Set paiseses) {
		this.idIdioma = idIdioma;
		this.idioma = idioma;
		this.paiseses = paiseses;
	}
	// Constructor que he creado sin el id
	public Idiomas(String idioma) {
		this.idioma = idioma;
	}
	
	public int getIdIdioma() {
		return this.idIdioma;
	}

	public void setIdIdioma(int idIdioma) {
		this.idIdioma = idIdioma;
	}

	public String getIdioma() {
		return this.idioma;
	}

	public void setIdioma(String idioma) {
		this.idioma = idioma;
	}

	public Set getPaiseses() {
		return this.paiseses;
	}

	public void setPaiseses(Set paiseses) {
		this.paiseses = paiseses;
	}

}
