package clasesHibernate;
// Generated 29 abr 2025 14:45:43 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Paises generated by hbm2java
 */
public class Paises implements java.io.Serializable {

	private int idPais;
	private String nombre;
	private Float numHabitantes;
	private Float superficie;
	private Float kmLineaCosta;
	private Float km2Agua;
	private Float km2Tierra;
	private Set practicareligioneses = new HashSet(0);
	private Set idiomases = new HashSet(0);
	private Set ciudadeses = new HashSet(0);

	public Paises() {
	}

	public Paises(int idPais) {
		this.idPais = idPais;
	}

	public Paises(int idPais, String nombre, Float numHabitantes, Float superficie, Float kmLineaCosta, Float km2Agua,
			Float km2Tierra, Set practicareligioneses, Set idiomases, Set ciudadeses) {
		this.idPais = idPais;
		this.nombre = nombre;
		this.numHabitantes = numHabitantes;
		this.superficie = superficie;
		this.kmLineaCosta = kmLineaCosta;
		this.km2Agua = km2Agua;
		this.km2Tierra = km2Tierra;
		this.practicareligioneses = practicareligioneses;
		this.idiomases = idiomases;
		this.ciudadeses = ciudadeses;
	}
	//Constructor añadido
	public Paises(String nombre, Float numHabitantes, Float superficie, Float kmLineaCosta, Float km2Agua,
			Float km2Tierra, Set practicareligioneses, Set idiomases, Set ciudadeses) {
		this.nombre = nombre;
		this.numHabitantes = numHabitantes;
		this.superficie = superficie;
		this.kmLineaCosta = kmLineaCosta;
		this.km2Agua = km2Agua;
		this.km2Tierra = km2Tierra;
		this.practicareligioneses = practicareligioneses;
		this.idiomases = idiomases;
		this.ciudadeses = ciudadeses;
	}

	public int getIdPais() {
		return this.idPais;
	}

	public void setIdPais(int idPais) {
		this.idPais = idPais;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Float getNumHabitantes() {
		return this.numHabitantes;
	}

	public void setNumHabitantes(Float numHabitantes) {
		this.numHabitantes = numHabitantes;
	}

	public Float getSuperficie() {
		return this.superficie;
	}

	public void setSuperficie(Float superficie) {
		this.superficie = superficie;
	}

	public Float getKmLineaCosta() {
		return this.kmLineaCosta;
	}

	public void setKmLineaCosta(Float kmLineaCosta) {
		this.kmLineaCosta = kmLineaCosta;
	}

	public Float getKm2Agua() {
		return this.km2Agua;
	}

	public void setKm2Agua(Float km2Agua) {
		this.km2Agua = km2Agua;
	}

	public Float getKm2Tierra() {
		return this.km2Tierra;
	}

	public void setKm2Tierra(Float km2Tierra) {
		this.km2Tierra = km2Tierra;
	}

	public Set getPracticareligioneses() {
		return this.practicareligioneses;
	}

	public void setPracticareligioneses(Set practicareligioneses) {
		this.practicareligioneses = practicareligioneses;
	}

	public Set getIdiomases() {
		return this.idiomases;
	}

	public void setIdiomases(Set idiomases) {
		this.idiomases = idiomases;
	}

	public Set getCiudadeses() {
		return this.ciudadeses;
	}

	public void setCiudadeses(Set ciudadeses) {
		this.ciudadeses = ciudadeses;
	}

}
