package clasesHibernate;
// Generated 29 abr 2025 14:45:43 by Hibernate Tools 6.5.1.Final

/**
 * Practicareligiones generated by hbm2java
 */
public class Practicareligiones implements java.io.Serializable {

	private PracticareligionesId id;
	private Religiones religiones;
	private Paises paises;
	private Float practicantes;

	public Practicareligiones() {
	}

	public Practicareligiones(PracticareligionesId id, Religiones religiones, Paises paises) {
		this.id = id;
		this.religiones = religiones;
		this.paises = paises;
	}

	public Practicareligiones(PracticareligionesId id, Religiones religiones, Paises paises, Float practicantes) {
		this.id = id;
		this.religiones = religiones;
		this.paises = paises;
		this.practicantes = practicantes;
	}

	public PracticareligionesId getId() {
		return this.id;
	}

	public void setId(PracticareligionesId id) {
		this.id = id;
	}

	public Religiones getReligiones() {
		return this.religiones;
	}

	public void setReligiones(Religiones religiones) {
		this.religiones = religiones;
	}

	public Paises getPaises() {
		return this.paises;
	}

	public void setPaises(Paises paises) {
		this.paises = paises;
	}

	public Float getPracticantes() {
		return this.practicantes;
	}

	public void setPracticantes(Float practicantes) {
		this.practicantes = practicantes;
	}

}
