package clasesHibernate;
// Generated 29 abr 2025 14:45:43 by Hibernate Tools 6.5.1.Final

/**
 * PracticareligionesId generated by hbm2java
 */
public class PracticareligionesId implements java.io.Serializable {

	private int idPais;
	private int idReligion;

	public PracticareligionesId() {
	}

	public PracticareligionesId(int idPais, int idReligion) {
		this.idPais = idPais;
		this.idReligion = idReligion;
	}

	public int getIdPais() {
		return this.idPais;
	}

	public void setIdPais(int idPais) {
		this.idPais = idPais;
	}

	public int getIdReligion() {
		return this.idReligion;
	}

	public void setIdReligion(int idReligion) {
		this.idReligion = idReligion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PracticareligionesId))
			return false;
		PracticareligionesId castOther = (PracticareligionesId) other;

		return (this.getIdPais() == castOther.getIdPais()) && (this.getIdReligion() == castOther.getIdReligion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPais();
		result = 37 * result + this.getIdReligion();
		return result;
	}

}
