package clasesHibernate;
// Generated 29 abr 2025 14:45:43 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Religiones generated by hbm2java
 */
public class Religiones implements java.io.Serializable {

	private int idReligion;
	private String nombre;
	private Set practicareligioneses = new HashSet(0);

	public Religiones() {
	}

	public Religiones(int idReligion) {
		this.idReligion = idReligion;
	}

	public Religiones(int idReligion, String nombre, Set practicareligioneses) {
		this.idReligion = idReligion;
		this.nombre = nombre;
		this.practicareligioneses = practicareligioneses;
	}
	// cONSTRUCTOR que creamos cuando corregimos el fichero de mapeo
	public Religiones(String nombre) {
		this.nombre = nombre;
	}
	
	public int getIdReligion() {
		return this.idReligion;
	}

	public void setIdReligion(int idReligion) {
		this.idReligion = idReligion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getPracticareligioneses() {
		return this.practicareligioneses;
	}

	public void setPracticareligioneses(Set practicareligioneses) {
		this.practicareligioneses = practicareligioneses;
	}

}
